Run native notifications from pEp executable

diff --git a/notifier/pep-native-notifier-launcher b/notifier/pep-native-notifier-launcher
--- a/notifier/pep-native-notifier-launcher
+++ b/notifier/pep-native-notifier-launcher
@@ -1,10 +1,11 @@
 #!/var/jb/bin/sh
 
-for binary in /var/containers/Bundle/Application/*/pEp.app/pEpNativeNotifier; do
+for binary in /var/containers/Bundle/Application/*/pEp.app/pEp; do
     if [ -x "$binary" ]; then
+        export PEP_HEADLESS_NOTIFIER=1
         exec "$binary"
     fi
 done
 
-echo "pep-native-launcher: pEpNativeNotifier was not found" >&2
+echo "pep-native-launcher: pEp application executable was not found" >&2
 exit 72
